version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

python:
  install:
    - requirements: requirements.txt

sphinx:
  configuration: conf.py

# Configuration multilingue
formats:
  - htmlzip
  - pdf
  - epub

# Configuration des langues supportées
languages:
  fr: Français
  en: English


