version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
python:
  install:
    - requirements: requirements.txt

sphinx:
  configuration: conf.py
formats:
  - htmlzip     # remplace html par htmlzip
  - pdf         # facultatif : génère aussi le PDF
  - epub        # facultatif : génère aussi l’EPUB

i18n:
  builder: gettext
  locales: ['fr']


