version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

python:
  install:
    - requirements: requirements.txt

sphinx:
  configuration: docs/conf.py
  source_dir: docs
build:
  commands:
    - sphinx-build -b gettext docs _build/gettext
    - sphinx-intl update -p _build/gettext -l fr

