version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"  
  jobs:
    pre_build:
      - python scripts/pre_build.py
    post_build:
      - bash scripts/post_build.sh

python:
  install:
    - requirements: requirements.txt

sphinx:
  configuration: conf.py
  fail_on_warning: false
  
# formats:
#   - htmlzip
#   - pdf
#   - epub

# Configuration multilingue
# localization:
#   languages:
#     - en
#     - fr


