name: Weblate Sync

on:
  push:
    branches: [ main ]
    paths:
      - 'locale/**'
  pull_request:
    branches: [ main ]

jobs:
  sync-weblate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinx-intl babel
    
    - name: Generate translation template
      run: |
        make gettext
    
    - name: Update translation files
      run: |
        sphinx-intl update -p _build/gettext -l en
    
    - name: Commit translation updates
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add locale/
        git diff --quiet && git diff --staged --quiet || git commit -m "Update translation files from Weblate"
        git push 